name: analyze

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.x'

      - name: Restore packages
        run: flutter pub get

      - name: Analyze
        if: always()
        run: flutter analyze
